### ISSUE TITLE
点击微信“确认登陆”没有回调onResp

### ISSUE THREAD

**Issue by xubuhang** [whilu/TPShareLogin#6]
@whilu 如题点击微信登陆没有回调onResp，请问怎么解决

**Comment by whilu** [comment]
好意思回复晚了，必须填写你自己正确并通过微信审核的APPID和APPSECRET，demo里面是没有这些的。

``` java
//参数分别为微博回调地址、微博APP KEY、微博APP SECRET、QQ APPID、QQ APPSECRET、微信APPID、微信APPSECRET
TPManager.getInstance().initAppConfig("",  "", "", "", "",  "", "");
```

**Comment by xubuhang** [comment]
@whilu 我确认我填写了，而且QQ的登录和分享可以，微信的分享可以。就是微信登录获取不到用户信息没有回调onResp。不知道哪里的原因？

**Comment by imlujun** [comment]
@xubuhang 微信登录的权限你的APP开通了吗？

**Comment by xubuhang** [comment]
@imlujun 注册app时候微信登录就是默认打开的。

**Comment by xubuhang** [comment]
@whilu @imlujun 我知道自己错在哪里了。我之前WXEntryActivity是应用包名.activity.wxapi 下,现在改成了应用包名.wxapi 下。坑死我了。谢谢二位。
