### ISSUE TITLE
 Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by xubuhang** [whilu/TPShareLogin#9]
添加了TPShareLogin后就清单文件合并失败了。
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
![qq 20170102232128](https://cloud.githubusercontent.com/assets/4189632/21591818/969cc6dc-d142-11e6-9bbb-d57ec1689173.png)

**Comment by xubuhang** [comment]
去掉我自己项目application的android:label="xxx"就好了。

**Comment by whilu** [comment]
@xubuhang 恩，你也可以使用```tools:replace=..``` 替换。
